# Generated by Django 5.1.6 on 2025-04-20 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_blacklistedaccesstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_title', models.CharField(choices=[('daily_login', 'Daily Login'), ('referral', 'Referral'), ('order', 'Order')], max_length=255)),
                ('value', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_date', models.DateField(auto_now_add=True, null=True)),
                ('order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('score_title', 'daily_login')), fields=('user', 'event_date'), name='unique_daily_login_per_user_per_day'), models.UniqueConstraint(fields=('user', 'order_id'), name='unique_order_per_user'), models.UniqueConstraint(fields=('user', 'referral_phone_number'), name='unique_referral_per_user')],
            },
        ),
    ]
