# Generated by Django 5.1.6 on 2025-04-24 15:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_scoreevent'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scoreevent',
            name='unique_daily_login_per_user_per_day',
        ),
        migrations.RemoveConstraint(
            model_name='scoreevent',
            name='unique_order_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='scoreevent',
            name='unique_referral_per_user',
        ),
        migrations.RenameField(
            model_name='scoreevent',
            old_name='score_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='scoreevent',
            name='value',
        ),
        migrations.AddField(
            model_name='user',
            name='total_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scoreevent',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scoreevent',
            name='referral_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='scoreevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='scoreevent',
            constraint=models.UniqueConstraint(condition=models.Q(('title', 'daily_login')), fields=('user', 'event_date'), name='unique_daily_login_per_user_per_day'),
        ),
        migrations.AddConstraint(
            model_name='scoreevent',
            constraint=models.UniqueConstraint(condition=models.Q(('title', 'order')), fields=('user', 'order_id'), name='unique_order_constraint'),
        ),
        migrations.AddConstraint(
            model_name='scoreevent',
            constraint=models.UniqueConstraint(condition=models.Q(('title', 'referral')), fields=('user', 'referral_phone_number'), name='unique_referral_constraint'),
        ),
    ]
