# Generated by Django 5.1.6 on 2025-03-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10, null=True),
        ),
    ]
