# Generated by Django 5.1.6 on 2025-03-05 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_price_productvariant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='store.collection'),
        ),
    ]
