# Generated by Django 5.1.6 on 2025-03-06 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_attributevalue_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='collection',
        ),
        migrations.AddField(
            model_name='attribute',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='store.collection'),
        ),
    ]
