# Generated by Django 5.1.6 on 2025-04-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_attribute_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='collection',
        ),
        migrations.AddField(
            model_name='collection',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='collections', to='store.attribute'),
        ),
    ]
