# Generated by Django 5.1.6 on 2025-04-12 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_attribute_options_alter_attributevalue_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='collection',
        ),
        migrations.AddField(
            model_name='collection',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcollections', to='store.collection', verbose_name=' مجموعه والد'),
        ),
    ]
