# Generated by Django 5.1.6 on 2025-04-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_collection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='collections/', verbose_name='تصویر دسته بندی'),
        ),
    ]
